// eslint-disable-next-line import/no-anonymous-default-export
export default [
  {
    id: "1",
    title: "Redragon K512",
    category: "keyboard",
    price: 20,
    images: [
      "https://m.media-amazon.com/images/I/71w9I5LAUZL.jpg",
      "https://m.media-amazon.com/images/I/71TCFwrskRL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71KGIiceY-L._AC_SX679_.jpg",
    ],
    description: "Redragon K512 RGB Keyboard Mechanical Feeling switches",
    count: 7,
    rating: 4,
    raters: 15,
    addedToCart: false,
    favourite: false,
  },
  {
    id: "2",
    title: "Redragon H320",
    category: "headphone",
    price: 32,
    images: [
      "https://m.media-amazon.com/images/I/61Oq9Iv8UhL.jpg",
      "https://m.media-amazon.com/images/I/51h+NmzYHLL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/51XmajOZATL._AC_SX679_.jpg",
    ],
    description: "Redragon H320 Headset",
    count: 3,
    rating: 3,
    raters: 6,
    addedToCart: false,
    favourite: false,
  },
  {
    id: "3",
    title: "Razer Basilisk X",
    category: "mouse",
    price: 38,
    images: [
      "https://m.media-amazon.com/images/I/81W3s4ZWMXL.jpg",
      "https://m.media-amazon.com/images/I/81iGgxdBcHL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71tmUKvm1eL._AC_SX679_.jpg",
    ],
    description:
      "Razer Basilisk X Hyperspeed Wireless Gaming Mouse: Bluetooth & Wireless Compatible",
    count: 2,
    rating: 5,
    raters: 2,
    addedToCart: false,
    favourite: false,
  },
  {
    id: "4",
    title: "Apple MacBook Pro 2020",
    category: "laptop",
    price: 1500,
    images: [
      "https://m.media-amazon.com/images/I/31MQgbpmcSL._AC_SY780_.jpg",
      "https://m.media-amazon.com/images/I/81AkdxBCVpL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/91xkiFp-lzL._AC_SX679_.jpg",
    ],
    description:
      "Apple MacBook Pro 2020 Model (13-Inch, Apple M1 chip with 8-core CPU and 8-core GPU, 8GB, 512GB, Touch Bar and Touch ID, MYD92 ), Eng-KB, Space Gray",
    count: 6,
    rating: 4,
    raters: 35,
    addedToCart: false,
    favourite: false,
  },
  {
    id: "5",
    title: "Lenovo Legion 5",
    category: "laptop",
    price: 1300,
    images: [
      "https://m.media-amazon.com/images/I/61gN58M6OXL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/41k52BqPcFL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/413yODSEKsL._AC_.jpg",
    ],
    description:
      "Lenovo Legion 5 15ITH6 Gaming laptop - 11th Intel Core i5-11400H 6-Cores, 16GB RAM, 1TB SSD, NVIDIA GeForce RTX 3060 6GB GDDR6 Graphics, 15.6 FHD IPS 165Hz, 4-Zone RGB Backlit - Dos - Phantom Blue",
    count: 3,
    rating: 3,
    raters: 26,
    addedToCart: false,
    favourite: false,
  },
  {
    id: "6",
    title: "HyperX Alloy",
    category: "keyboard",
    price: 100,
    images: [
      "https://m.media-amazon.com/images/I/71HV-xAiyML._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/918ZagKPirL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/81s09Lsv-mL._AC_SX679_.jpg",
    ],
    description: "HyperX Alloy OriginsTM 60 Mechanical Gaming Keyboard",
    count: 8,
    rating: 5,
    raters: 49,
    addedToCart: false,
    favourite: false,
  },
  {
    id: "7",
    title: "Redragon K530 Draconic",
    category: "keyboard",
    price: 60,
    images: [
      "https://m.media-amazon.com/images/I/61kEZ+2VX+L._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71Ck5iSwVtL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71pvd5LWgwL._AC_SX679_.jpg",
    ],
    description:
      "Redragon K530 Draconic 60% Compact RGB Wireless Mechanical Keyboard, 61 Keys TKL Designed 5.0 Bluetooth Gaming Keyboard with Brown Switches and 16.8 Million RGB Lighting",
    count: 5,
    rating: 4,
    raters: 54,
    addedToCart: false,
    favourite: false,
  },
  {
    id: "8",
    title: "HP 15-dw3033dx Laptop",
    category: "laptop",
    price: 600,
    images: [
      "https://m.media-amazon.com/images/I/81qohiv33aL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/81mlhJq4JbL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71yZp-Ru4WL._AC_SX679_.jpg",
    ],
    description:
      "HP 15-dw3033dx Laptop - 11th Intel core i3-1115G4, 8GB RAM, 256GB SSD, Intel UHD Graphics, 15.6 FHD (1920 x 1080) IPS micro-edge anti-glare 250 nits, FingerPrint, Windows 10, Natural Silver",
    count: 3,
    rating: 4,
    raters: 35,
    addedToCart: false,
    favourite: false,
  },
];
